name: Python App

# Trigger the workflow on any push to the master branch or any pull request
on: 
    push:
        branches: [ "master" ]  # It can have multiple branches
    pull_request: 
        branches: [ "master" ]  # It can have multiple branches

jobs:
    test:
        runs-on: 'ubuntu-latest'  # Can be windows, mac etc.

        steps:
        # Step 1: Checkout the code from the repository
        - name: Check out code
          uses: actions/checkout@v3

        # Step 2: Setting up python environment
        - name: Set up python 3.9
          uses: actions/setup-python@v3
          with:
            python-version: "3.9"

        # Step 3: Install dependencies
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            
        # Step 4: Run tests
        - name: Run Tests
          run: |
            pytest
